### ISSUE TITLE
Host Routes return a value of "None" for network address and netmask

### ISSUE THREAD

**Issue by bobbywatson3** [drybjed/ansible-ipaddr-filter#1]
If a host route is given to ipaddr (for example 192.168.1.100/32), the ipaddr('network') and ipaddr('netmask') are outputted as "None" instead of 192.168.1.100 for the network, and 255.255.255.255 for the netmask. 

yaml file: 

```

---
- name: ipaddr host route test
  hosts: all
  connection: local
  gather_facts: no
  vars:
    example_host_route: 192.168.1.100/32

  tasks: 
    - name: example
      local_action: template src=config_template.j2 dest=/tmp/example
```

config_template.j2:

```
Route: {{ example_host_route }}
Network: {{ example_host_route | ipaddr('network') }}
Netmask: {{ example_host_route | ipaddr('netmask') }}
```

Output:

```
$ ansible-playbook host_route.yml -i localhost && cat /tmp/example

PLAY [ipaddr host route test] ************************************************* 

TASK: [example] *************************************************************** 
changed: [localhost -> 127.0.0.1]

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=1    unreachable=0    failed=0   

Route: 192.168.1.100/32
Network: None
Netmask: None
```
